邮件发送成功
邮件发送成功
邮件发送成功
邮件发送成功
python: can't open file '/exp/home/luxi.xiao/My_code/My_code/reminder.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/exp/home/luxi.xiao/My_code/reminder.py", line 23, in <module>
    reminder()
TypeError: reminder() missing 2 required positional arguments: 'logfile' and 'pid_to_monitor'
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: unrecognized arguments: --pid_to_prosscess 123 &
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: unrecognized arguments: &
Traceback (most recent call last):
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/_common.py", line 491, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/exp/home/luxi.xiao/My_code/reminder.py", line 38, in <module>
    reminder(input_logfile,input_pid_to_monitor)
  File "/exp/home/luxi.xiao/My_code/reminder.py", line 24, in reminder
    output = monitor_pid.output_status(pid_to_monitor) #监测进程状态，并赋值到output
  File "/exp/home/luxi.xiao/My_code/monitor_pid.py", line 17, in output_status
    status = check_process(PID_TO_MONITOR)
  File "/exp/home/luxi.xiao/My_code/monitor_pid.py", line 8, in check_process
    process = psutil.Process(pid)
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/__init__.py", line 323, in __init__
    self._init(pid)
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/__init__.py", line 359, in _init
    self.create_time()
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/__init__.py", line 752, in create_time
    self._create_time = self._proc.create_time()
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/_pslinux.py", line 1714, in wrapper
    return fun(self, *args, **kwargs)
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/_pslinux.py", line 1945, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/_pslinux.py", line 1714, in wrapper
    return fun(self, *args, **kwargs)
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/_common.py", line 495, in wrapper
    return fun(self)
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/_pslinux.py", line 1777, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/_common.py", line 840, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
  File "/exp/home/luxi.xiao/miniconda3/envs/email/lib/python3.9/site-packages/psutil/_common.py", line 829, in cat
    return f.read()
KeyboardInterrupt
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: unrecognized arguments: 123
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: unrecognized arguments: --pid_to_porcess 123
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: argument --logfile/-f: expected one argument
邮件发送成功
2024-04-28 13:09:02
邮件发送成功
2024-04-28 13:12:26
邮件发送成功
2024-04-28 13:15:58
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: argument --logfile/-f: expected one argument
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: argument --logfile/-f: expected one argument
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: argument --logfile/-f: expected one argument
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: argument --logfile/-f: expected one argument
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: argument --logfile/-f: expected one argument
邮件发送成功
2024-04-28 13:50:19
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: argument --logfile/-f: expected one argument
usage: reminder.py [-h] [--pid_to_process PID_TO_PROCESS] [--logfile LOGFILE]
reminder.py: error: argument --logfile/-f: expected one argument
邮件发送成功
2024-04-28 13:53:55
邮件发送成功
2024-04-28 13:54:30
邮件发送成功
2024-04-28 13:56:05
邮件发送成功
2024-04-28 13:58:22
邮件发送成功
2024-04-28 21:09:27
